<?php

namespace Tests\Repositories;

use App\Repositories\PostRepository;
use Illuminate\Support\Facades\Log;
use Tests\TestCase;

class PostRepositoryTest extends TestCase
{
    private PostRepository $postRepository;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->postRepository = new PostRepository();
    }

    public function testCollectScheduleSuccess()
    {
        $limit = 6;
        $collection = $this->postRepository->listOfPublishedScheduleWith($limit);
        Log::debug(json_encode($collection));
        self::assertCount($limit, $collection);
    }

    public function testCollectNewsSuccess()
    {
        $collection = $this->postRepository->listOfSpotlightPublishedNews();
        self::assertCount(6, $collection);
    }
}
